### PR TITLE
Use apt package and add docker-compose

### PR DESCRIPTION
**Pull request by mattstep**
Just providing some changes I made to get this working on my home network. I run a 4gb rock pro 64, so aarch64 is what I needed instead of amd64. It runs great. Feel free to cherrypick off this or whatnot.

### CODE REVIEW

**Comment by fryfrog** [comment]
So I *think* if you take my `Dockerfile` and name it like `Dockerfile.aarch64`, it'll just work for everyone. This specific `unifi-protect` as intended for amd64 systems. I may have the exact naming wrong though, so a quick bit of research / example images wouldn't be crazy.

**Comment by mattstep** [comment]
I think they pulled the amd64 package unfortunately, so I wasn't able to get the original dockerfile to work. Feel free to modify this however you want, just trying to contribute back if you want it. Thanks for your efforts on this, super helpful!

**Comment by fryfrog** [comment]
Yeah, they pulled it but it is built and on Docker Hub so it doesn't really matter. You can't use the aarch64 on amd64, so I'm not going to *convert* this. I'll just leave this here, which ever of us makes it correct first "wins". :)

**Comment by mattstep** [comment]
Sounds good, if I have a minute tonight I might do it. Cheers!

**Pull request closed without merging**
